# Generated by Django 4.1.2 on 2022-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
